HOROVOD_CUDA_HOME=$1 \
HOROVOD_NCCL_HOME=$2 \
HOROVOD_WITHOUT_GLOO=1 \
HOROVOD_WITH_MPI=1 \
HOROVOD_GPU=CUDA \
HOROVOD_GPU_OPERATIONS=NCCL \
HOROVOD_CPU_OPERATIONS=MPI \
HOROVOD_WITH_TENSORFLOW=1 \
HOROVOD_WITHOUT_PYTORCH=1 \
HOROVOD_WITHOUT_MXNET=1 \
pip3 install --user --no-cache-dir horovod==0.16


